language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

# Coverage submission currently broken due to
#     https://github.com/JuliaWeb/MbedTLS.jl/issues/193
# coveralls: true
